### PR TITLE
Added ASCII tribute to Diana, Princess of Wales

### PR DESCRIPTION
**Pull request by richarddomino**
Queen of hearts. Miss you big man.

### CODE REVIEW

**Comment by richarddomino** [comment]
Hi Rod, this is approaching a month now and we really need this merged as a priority

**Comment by rodnaph** [comment]
Hi Richard, I'm afraid I'm waiting to see how the Trump campaign affects international opinion on the memory of Diana "Queen of Hearts", Princess of Wales before making a decision.  I'm sure you understand.

**Comment by richarddomino** [comment]
Rod, we're unable to use this tool at Domino without this - we don't like to have to deploy/maintain a custom version, we'd really rather see it merged.

**Comment by rodnaph** [comment]
I've reviewed your fork again and would like to see the number of commits in this repository to increase and at least match the number of commits Github displays for the master branch of your fork. So I'm going to merge this, thanks for all your hard work Domino.

**Comment by richarddomino** [comment]
Appreciated.

**Pull request merged**
